on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  schedule:
    - cron: "0 0 1 * *"
  workflow_dispatch:

jobs:
  send-emails:
    runs-on: [self-hosted, windows, x64]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        shell: cmd
        run: go build -o eraser.exe .

      - name: Send emails
        shell: cmd
        run: eraser.exe send
